### ISSUE TITLE
Remove from dock, how do I get it back?

### ISSUE THREAD

**Issue by tgienger** [rhoconlinux/plank-themer#3]
Like the title says, I have removed plank-themer from the dock and not sure how to get it back.

**Comment by rhoconlinux** [comment]
There are two ways: 

1) From the terminal: (paste this code)

<code>
cp ~/.config/plank/dock1/theme_index/plank-themer-ondock.dockitem ~/.config/plank/dock1/launchers
</code>

Tadaaa! :dancers: 

2) Manually: you should drag and drop this folder <code>~/.config/plank/dock1/theme_index/plank-themer-ondock</code> to plank. Done! :+1: 

:)

**Comment by Foggalong** [comment]
This isn't really a fix - there should be a way to do this through the GUI
